name: WebdriverIO Smoke Suite
on:
  pull_request:
    branches: main

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install Packages
          run: npm ci
        - name: Run Test
          run: npm run smoke